### ISSUE TITLE
ユーザー管理

### ISSUE THREAD

**Issue by takapiro99** [jphacks/A_2111#34]
ちゃんとしたユーザー登録とかはしないで、簡易的にユーザー管理します！

- 起動時、appcontextのuseEffect内でlocalstorageを見に行きます
- idがあったら、それでログインしたとみなします
- なかったら、
  - 新規登録画面（又はモーダル？）を出し、なまえを入力させる
  - それをサーバーに送信し、IDをもらってくる（サーバー未デプロイ）
  - それをLocalstorageに保存し、ログインしたこととする
- ログイン情報などは、appcontextのstateで管理する

**Comment by Nano3013** [comment]
できた！
