### ISSUE TITLE
ハードウェアアップデート

### ISSUE THREAD

**Issue by gojiteji** [jphacks/A_2111#73]
ファッションアイテムへの対応

**Comment by gojiteji** [comment]
A transition from Raspberry Pi Zero to ESP32 might be needed because of the cost.

**Comment by gojiteji** [comment]
ハードウェアの色・デザインもアプリに揃える

**Comment by gojiteji** [comment]
バッテリー交換もしくは充電方法の簡略化

**Comment by Nano3013** [comment]
たかぴろさん言ってたように帽子に搭載したりして、外出ても違和感ないように出来ないですかね
