### ISSUE TITLE
ワクチン関連情報の表示

### ISSUE THREAD

**Issue by gojiteji** [jphacks/A_2111#94]

**Comment by gojiteji** [comment]
ワクチン接種会場の表示
ワクチンあまりの表示

**Comment by gojiteji** [comment]
COCOAの仕組み解説コーナー

**Comment by gojiteji** [comment]
Youtube,Instagramは"コロナを知る"的な誘導が存在した(スクショ取ろうと思ったけど丁度今はなかった)

**Comment by gojiteji** [comment]
位置情報や行動履歴に基づいたコロナニュースのピックアップ

**Comment by USK314** [comment]
ワクチン関連情報だと確かに今回のプロダクトに関係はしているけど少し逸れてる気がします(目覚ましアプリにニュースがついていても多分見ない)

あくまでマスクアプリだということを考慮して情報をまとめるとしたらマスク関連に限定したほうが良いのかなと思いました
ex.)マスクの正しい付け方、マスクの素材の違い、ウイルスの滞空距離…
