### ISSUE TITLE
マスクの紐の長さを調整したい

### ISSUE THREAD

**Issue by USK314** [jphacks/A_2111#99]
アプリの起動時に毎度S/M/Lを選択させる
or
紐の長さ情報を登録しておく

**Comment by takapiro99** [comment]
ユーザー登録時に登録しておくようにしつつ、名前変更のエンドポイントでマスクの大きさも一緒に入れれるようにしたらいいかなって思ってました！

意見も止めます！

**Comment by takapiro99** [comment]
あ（テスト）

**Comment by USK314** [comment]
とりあえずその方向で進めます！

**Comment by USK314** [comment]
バックエンドは実装完了したから一回閉じる
